workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 15
    integrations:
      app_store_connect: Emerson Stewart
    environment:
      groups:
        - default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.taskwire.ios
      vars:
        APP_ID: 6747297758
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter generate icons
        script: |
          flutter pub run flutter_launcher_icons
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

  windows-workflow:
      name: Windows workflow
      instance_type: windows_x2
      max_build_duration: 15
      environment:
        flutter: stable
        groups:
          - default
        vars:
          CM_TAG: $CM_TAG
      cache:
        cache_paths:
          - ~/.pub-cache
      scripts:
        - name: Get Flutter packages
          script: flutter packages pub get
        - name: Configure for Windows
          script: flutter config --enable-windows-desktop
        - name: Flutter generate icons
          script: |
            flutter pub run flutter_launcher_icons
        - name: Build Windows
          script: flutter build windows
        - name: Build MSI
          script: |
            cd windows/installer
            ./build_msi.bat
        - name: Publish to GitHub
          script: |
            if ([string]::IsNullOrEmpty($env:CM_TAG)) {
              Write-Host "Error: CM_TAG is empty"
              exit 0
            }
            
            # Check if release exists, create if it doesn't
            try {
              gh release view "$env:CM_TAG" 2>$null | Out-Null
              Write-Host "Release $env:CM_TAG already exists, uploading artifacts"
            } catch {
              Write-Host "Creating GitHub release $env:CM_TAG"
              gh release create "$env:CM_TAG" --title "TaskWire $env:CM_TAG" --notes "TaskWire $env:CM_TAG"
            }
            
            # Upload artifacts to the release
            gh release upload "$env:CM_TAG" windows/installer/TaskWire.msi
      artifacts:
        - windows/installer/TaskWire.msi
      triggering:
        events:
          - tag
        branch_patterns:
          - pattern: "main"
            include: true
            source: true

  windows-release-workflow:
    name: Windows release workflow
    instance_type: windows_x2
    max_build_duration: 15
    environment:
      groups:
        - default
        - windows-signing
      flutter: master
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Configure for Windows
        script: flutter config --enable-windows-desktop
      - name: Flutter generate icons
        script: |
          flutter pub run flutter_launcher_icons
      - name: Build Windows
        script: flutter build windows
      - name: Package Windows
        script: flutter pub run msix:create
    artifacts:
      - build/windows/**/*.msix

  linux-workflow:
    name: Linux Release Workflow
    instance_type: linux_x2
    max_build_duration: 15
    environment:
      groups:
        - default
      flutter: master
      vars:
          CM_TAG: $CM_TAG
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name : Install AppImage
        script: |
          sudo apt install locate wget
          wget -O appimagetool "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/
      - name: Install Fastforge
        script: dart pub global activate fastforge && export PATH=$PATH:$HOME/.pub-cache/bin
      - name: Build deb package
        script: fastforge package --platform linux --targets deb
      - name: Publish to GitHub
        script: | 
          #!/usr/bin/env zsh

          # Publish only for tag builds
          if [ -z ${CM_TAG} ]; then
            echo "Not a tag build, will not publish GitHub release"
            exit 0
          fi

          # Check if release exists, create if it doesn't
          if ! gh release view "${CM_TAG}" > /dev/null 2>&1; then
            echo "Creating GitHub release ${CM_TAG}"
            gh release create "${CM_TAG}" \
              --title "TaskWire ${CM_TAG}" \
              --notes "TaskWire release ${CM_TAG}"
          else
            echo "Release ${CM_TAG} already exists, uploading artifacts"
          fi

          # Upload artifacts to the release
          gh release upload "${CM_TAG}" \
            dist/**/taskwire*.deb \
            dist/**/taskwire*.AppImage
    artifacts:
      - dist/**/taskwire*.deb
      - dist/**/taskwire*.AppImage
    triggering:
        events:
          - tag
        branch_patterns:
          - pattern: "main"
            include: true
            source: true