workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 15
    integrations:
      app_store_connect: Emerson Stewart
    environment:
      groups:
        - default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.taskwire.ios
      vars:
        APP_ID: 6747297758
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter generate icons
        script: |
          flutter pub run flutter_launcher_icons
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

  windows-workflow:
      name: Windows workflow
      instance_type: windows_x2
      max_build_duration: 15
      environment:
        flutter: stable
        groups:
          - default
      cache:
        cache_paths:
          - ~/.pub-cache
      scripts:
        - name: Get Flutter packages
          script: flutter packages pub get
        - name: Configure for Windows
          script: flutter config --enable-windows-desktop
        - name: Flutter generate icons
          script: |
            flutter pub run flutter_launcher_icons
        - name: Build Windows
          script: flutter build windows
        - name: Build MSI
          script: |
            cd windows/installer
            ./build_msi.bat
        - name: Publish to GitHub
          script: |
            gh release create "${CM_TAG}" \
              --title "TaskWire ${CM_TAG}" \
              windows/installer/TaskWire.msi \
              --clobber
      artifacts:
        - windows/installer/TaskWire.msi
      triggering:
        events:
          - tag
        branch_patterns:
          - pattern: "main"
            include: true
            source: true

  windows-release-workflow:
    name: Windows release workflow
    instance_type: windows_x2
    max_build_duration: 15
    environment:
      groups:
        - default
        - windows-signing
      flutter: master
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Configure for Windows
        script: flutter config --enable-windows-desktop
      - name: Flutter generate icons
        script: |
          flutter pub run flutter_launcher_icons
      - name: Build Windows
        script: flutter build windows
      - name: Package Windows
        script: flutter pub run msix:create
    artifacts:
      - build/windows/**/*.msix
